[client]
showErrorDetails = true
[theme]

# The preset Streamlit theme that your custom theme inherits from.
# One of "light" or "dark".
base ='light'

# Primary accent color for interactive elements.
primaryColor ='#F2BED1'

# Background color for the main content area.
backgroundColor ='#F9F5F6'

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor ='#F8E8EE'

# Color used for almost all text.
textColor ='#1B262C'

# Font family for all text in the app, except code blocks. One of "sans serif",
# "serif", or "monospace".
font ="monospace"